compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  rootly:
    npmAlwaysAuth: true
    npmAuthToken: NPM_TOKEN

yarnPath: .yarn/releases/yarn-4.4.0.cjs
